// SheetHash: 72B4ED303DA3669C28413DAE6C86E14AE0BFCD1135E4BAC613A7B86820918669
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Loose'
// </auto-generated>
#pragma once

#include "CoreMinimal.h"

#include "FLooseRow.generated.h"



/// <summary>시트 'Loose'의 한 행.</summary>
USTRUCT(BlueprintType)
struct FLooseRow
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Value = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name = TEXT("");
};