// SheetHash: 5251993D2D49B7D4D9049CCA94E051BFC57B8E18BDDDBE6C314A1C2773944891
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Mine_Stat'
// </auto-generated>
#pragma once

#include "CoreMinimal.h"

#include "FMine_StatRow.generated.h"

struct FStageRow;
struct FMineRow;

/// <summary>시트 'Mine_Stat'의 한 행.</summary>
USTRUCT(BlueprintType)
struct FMine_StatRow
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Group = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Stage_ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Mine_Stat_ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Mine_ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Spawn_Weight = 0.0f;

    /// <summary>Stage_ID FK가 가리키는 'Stage' 시트의 행을 돌려준다.</summary>
    template <typename TDatabase>
    const FStageRow& GetStage_ID(TDatabase& Database) const
    {
        return Database.GetStage(Stage_ID);
    }

    /// <summary>Mine_ID FK가 가리키는 'Mine' 시트의 행을 돌려준다.</summary>
    template <typename TDatabase>
    const FMineRow& GetMine_ID(TDatabase& Database) const
    {
        return Database.GetMine(Mine_ID);
    }
};