// SheetHash: D9825BD5547099F2741B8763B471157867DEA90C721A03CCDD8BF518C62739CD
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Mine'
// </auto-generated>
#pragma once

#include "CoreMinimal.h"

#include "FMineRow.generated.h"



/// <summary>시트 'Mine'의 한 행.</summary>
USTRUCT(BlueprintType)
struct FMineRow
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Mine_ID = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name = TEXT("");
};