[GoogleSheet]
# ServiceAccount | ApiKey | Local
AuthMode = ServiceAccount
SpreadsheetId =
ServiceAccountJsonPath = ./credentials/service-account.json
ApiKey =
LocalDirectory =
Sheets =

[CodeGen]
# Unity | Unreal
Target = Unreal
Namespace = BS.Data
DatabaseClassName = SheetDataBase
DatabaseOutputDirectory = ./Generated/Database
StructOutputDirectory = ./Generated/Database/Structs

[Json]
OutputPath = ./Generated/SheetDataBase.json
