[GoogleSheet]
# ServiceAccount | ApiKey | Local
AuthMode = ServiceAccount
SpreadsheetId =
ServiceAccountJsonPath = 
ApiKey =
LocalDirectory =
Sheets =

[CodeGen]
# Unity | Unreal
Target = Unity
Namespace = 
DatabaseClassName = SheetDataBase
DatabaseOutputDirectory = ./Generated/Database
StructOutputDirectory = ./Generated/Database/Structs

[Json]
OutputPath = ./Generated/SheetDataBase.json
