[GoogleSheet]
# ServiceAccount | ApiKey | Local
AuthMode = ServiceAccount
SpreadsheetId =
ServiceAccountJsonPath = ./credentials/service-account.json
ApiKey =
LocalDirectory =
Sheets =

[CodeGen]
# Unity | Unreal
Target = Unity
Namespace = BS.Data
DatabaseClassName = SheetDataBase
DatabaseOutputDirectory = ./Assets/Generated/Database
StructOutputDirectory = ./Assets/Generated/Database/Structs

[Json]
OutputPath = ./Assets/StreamingAssets/SheetDataBase.json
