// SheetHash: 72B4ED303DA3669C28413DAE6C86E14AE0BFCD1135E4BAC613A7B86820918669
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Loose'
// </auto-generated>
using System;

namespace Generated.Schema
{
    /// <summary>시트 'Loose'의 한 행.</summary>
    [Serializable]
    public partial struct SLooseRow
    {
        public int Value;
        public string Name;
    }
}