// SheetHash: D9825BD5547099F2741B8763B471157867DEA90C721A03CCDD8BF518C62739CD
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Mine'
// </auto-generated>
using System;

namespace Generated.Schema
{
    /// <summary>시트 'Mine'의 한 행.</summary>
    [Serializable]
    public partial struct SMineRow
    {
        public int Mine_ID;
        public string Name;
    }
}