// SheetHash: 5251993D2D49B7D4D9049CCA94E051BFC57B8E18BDDDBE6C314A1C2773944891
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Mine_Stat'
// </auto-generated>
using System;

namespace Generated.Schema
{
    /// <summary>시트 'Mine_Stat'의 한 행.</summary>
    [Serializable]
    public partial struct SMine_StatRow
    {
        public int Group;
        public int Stage_ID;
        public int Mine_Stat_ID;
        public int Mine_ID;
        public float Spawn_Weight;

        /// <summary>Stage_ID FK가 가리키는 'Stage' 시트의 행을 돌려준다.</summary>
        public SStageRow GetStage_ID(SheetDataBase database)
        {
            return database.GetStage(this.Stage_ID);
        }

        /// <summary>Mine_ID FK가 가리키는 'Mine' 시트의 행을 돌려준다.</summary>
        public SMineRow GetMine_ID(SheetDataBase database)
        {
            return database.GetMine(this.Mine_ID);
        }
    }
}