// SheetHash: E9334B4FF532061D4D523F3C63BCA6523A3F144FC91E67FB24EBFBDC40FDF350
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 시트 'Stage'
// </auto-generated>
using System;

namespace Generated.Schema
{
    /// <summary>시트 'Stage'의 한 행.</summary>
    [Serializable]
    public partial struct SStageRow
    {
        public string Name;
        public int Stage_ID;
    }
}