using System.Text;
using DataBuilder.Configuration;
using DataBuilder.Model;

namespace DataBuilder.CodeGen
{
	public enum EGenerateResult
	{
		Generated,
		SkippedByHash,
	}

	public abstract class CodeGeneratorBase : ICodeGenerator
	{
		private const string _HASH_COMMENT_PREFIX = "// SheetHash: ";
		protected const string AUTO_GENERATED_HEADER_TEMPLATE = "AUTO_GENERATED_HEADER";

		private readonly bool _force;

		protected CodeGeneratorBase(BuilderConfig config, IReadOnlyList<SheetTable> tables, EnumRegistry enums, bool force, string templateFileName)
		{
			Config = config;
			Tables = tables;
			TablesByName = tables.ToDictionary(t => t.Name, StringComparer.OrdinalIgnoreCase);
			Enums = enums;
			_force = force;
			Template = new CodeTemplate(templateFileName);
		}

		protected BuilderConfig Config
		{
			get;
		}

		protected IReadOnlyList<SheetTable> Tables
		{
			get;
		}

		protected Dictionary<string, SheetTable> TablesByName
		{
			get;
		}

		protected EnumRegistry Enums
		{
			get;
		}

		protected CodeTemplate Template
		{
			get;
		}

		public abstract void GenerateAll();

		protected static void Report(string path, EGenerateResult result)
		{
			string label = result == EGenerateResult.Generated ? "[생성]" : "[스킵]";
			string suffix = result == EGenerateResult.SkippedByHash ? " (동일한 해시의 파일이 이미 존재)" : string.Empty;
			Console.WriteLine($"  {label} {path}{suffix}");
		}

		protected EGenerateResult WriteFile(string path, string hash, Func<string> generateBody)
		{
			if (_force == false && File.Exists(path))
			{
				using StreamReader reader = new StreamReader(path);
				string? firstLine = reader.ReadLine();

				if (firstLine == _HASH_COMMENT_PREFIX + hash)
				{
					return EGenerateResult.SkippedByHash;
				}
			}

			string sourceCode = _HASH_COMMENT_PREFIX + hash + Environment.NewLine + generateBody();
			File.WriteAllText(path, sourceCode, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
			return EGenerateResult.Generated;
		}

		protected string CreateAutoGeneratedHeader(string origin)
		{
			return Template.Render(AUTO_GENERATED_HEADER_TEMPLATE, ("ORIGIN", origin));
		}

		protected string EnumsHash()
		{
			string source = string.Concat(Enums.Enums.Select(e => e.Key + string.Concat(e.Value)));
			return HashUtility.Sha256Hex(source);
		}

		protected string DatabaseHash()
		{
			return HashUtility.Sha256Hex(string.Concat(Tables.Select(t => t.Hash)));
		}

		protected static string Indent(string text, int spaceCount)
		{
			if (string.IsNullOrEmpty(text))
			{
				return string.Empty;
			}

			string indent = new string(' ', spaceCount);
			string[] lines = text.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", Environment.NewLine).Split(new[] { Environment.NewLine }, StringSplitOptions.None);
			return string.Join(Environment.NewLine, lines.Select(line => line.Length == 0 ? line : indent + line));
		}
	}
}
