using DataBuilder.Configuration;
using DataBuilder.Model;

namespace DataBuilder.CodeGen
{
	/// <summary>
	/// 시트 정의로부터 Unity용 C# 코드를 생성한다.
	/// 모든 생성 파일의 첫 줄에는 "// SheetHash: ..." 주석이 달리며,
	/// 같은 해시를 가진 파일이 이미 있으면 다시 생성하지 않고 그 파일을 사용한다.
	/// </summary>
	public sealed class UnityCodeGenerator : CodeGeneratorBase
	{
		private const string _TEMPLATE_FILE_NAME = "UnityCodeTemplates.txt";
		private const string _ENUMS_FILE_TEMPLATE = "ENUMS_FILE";
		private const string _ENUM_BLOCK_TEMPLATE = "ENUM_BLOCK";
		private const string _STRUCT_FILE_TEMPLATE = "STRUCT_FILE";
		private const string _REF_GETTER_BLOCK_TEMPLATE = "REF_GETTER_BLOCK";
		private const string _LIST_REF_GETTER_BLOCK_TEMPLATE = "LIST_REF_GETTER_BLOCK";
		private const string _DATA_GETTER_BLOCK_TEMPLATE = "DATA_GETTER_BLOCK";
		private const string _DATABASE_FILE_TEMPLATE = "DATABASE_FILE";
		private const string _INDEX_FIELD_BLOCK_TEMPLATE = "INDEX_FIELD_BLOCK";
		private const string _GETTER_BLOCK_TEMPLATE = "GETTER_BLOCK";
		private const string _INDEX_BUILD_BLOCK_TEMPLATE = "INDEX_BUILD_BLOCK";
		private const string _DATA_INDEX_FIELD_BLOCK_TEMPLATE = "DATA_INDEX_FIELD_BLOCK";
		private const string _DATA_DATABASE_GETTER_BLOCK_TEMPLATE = "DATA_DATABASE_GETTER_BLOCK";
		private const string _DATA_INDEX_BUILD_BLOCK_TEMPLATE = "DATA_INDEX_BUILD_BLOCK";
		private const string _DATA_LIST_INDEX_BUILD_BLOCK_TEMPLATE = "DATA_LIST_INDEX_BUILD_BLOCK";

		/// <summary>Unity 코드 생성에 필요한 설정과 시트 모델을 보관한다.</summary>
		public UnityCodeGenerator(BuilderConfig config, IReadOnlyList<SheetTable> tables, EnumRegistry enums, bool force) : base(config, tables, enums, force, _TEMPLATE_FILE_NAME)
		{
		}

		/// <summary>enum, 시트 구조체, 데이터베이스 클래스를 모두 생성한다.</summary>
		public override void GenerateAll()
		{
			Directory.CreateDirectory(Config.StructDirectory);
			Directory.CreateDirectory(Config.OutputDirectory);

			if (Enums.IsEmpty == false)
			{
				string enumPath = Path.Combine(Config.StructDirectory, "SheetEnums.generated.cs");
				Report(enumPath, WriteFile(enumPath, EnumsHash(), GenerateEnums));
			}

			foreach (SheetTable table in Tables)
			{
				string structPath = Path.Combine(Config.StructDirectory, table.StructName + ".generated.cs");
				Report(structPath, WriteFile(structPath, table.Hash, () => GenerateStruct(table)));
			}

			string databasePath = Path.Combine(Config.OutputDirectory, Config.DatabaseClassName + ".generated.cs");
			Report(databasePath, WriteFile(databasePath, DatabaseHash(), GenerateDatabase));
		}

		/// <summary>시트 enum 컬럼에서 enum 코드를 생성한다.</summary>
		private string GenerateEnums()
		{
			string enumBlocks = string.Join(Environment.NewLine + Environment.NewLine, Enums.Enums.Select(CreateEnumBlock));
			return Template.Render(_ENUMS_FILE_TEMPLATE, ("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("시트의 enum: 컬럼")), ("NAMESPACE", Config.Namespace), ("ENUM_BLOCKS", Indent(enumBlocks, 4)));
		}

		/// <summary>enum 타입 코드 블록을 만든다.</summary>
		private string CreateEnumBlock(KeyValuePair<string, List<string>> enumPair)
		{
			string members = string.Join(Environment.NewLine, enumPair.Value.Select((member, index) => $"{member} = {index},"));
			return Template.Render(_ENUM_BLOCK_TEMPLATE, ("ENUM_NAME", enumPair.Key), ("ENUM_MEMBERS", Indent(members, 4)));
		}

		/// <summary>컬럼 원소가 C# 코드에서 갖는 스칼라 타입 이름.</summary>
		private static string CSharpScalarTypeOf(ColumnSpec column)
		{
			return column.Type switch
			{
				EColumnType.Int => "int",
				EColumnType.Long => "long",
				EColumnType.Float => "float",
				EColumnType.Double => "double",
				EColumnType.Bool => "bool",
				EColumnType.String => "string",
				EColumnType.Enum => column.EnumName,
				_ => throw new InvalidOperationException($"지원하지 않는 컬럼 타입입니다: {column.Type}"),
			};
		}

		/// <summary>컬럼이 C# 코드에서 갖는 전체 타입 이름.</summary>
		private static string CSharpTypeOf(ColumnSpec column)
		{
			string scalarType = CSharpScalarTypeOf(column);
			return column.IsList ? $"List<{scalarType}>" : scalarType;
		}

		/// <summary>시트 하나에 대응하는 행 구조체 코드를 생성한다.</summary>
		private string GenerateStruct(SheetTable table)
		{
			string fieldLines = string.Join(Environment.NewLine, table.Columns.Select(column => $"public {CSharpTypeOf(column)} {column.FieldName};"));
			string refGetterBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                    table.Columns.Where(c => c.Role == EColumnRole.ForeignKey && c.IsList == false).Select(CreateRefGetterBlock)
			                                         .Concat(table.Columns.Where(c => c.IsList && (c.Role is EColumnRole.ForeignKey or EColumnRole.DataKey))
			                                                              .Select(CreateListRefGetterBlock)));
			string dataGetterBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                     OwnedDataOf(table).Select(relation => CreateDataGetterBlock(table, relation)));
			string accessorBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                    new[] { refGetterBlocks, dataGetterBlocks }.Where(text => string.IsNullOrWhiteSpace(text) == false));
			string memberBlocks = string.IsNullOrWhiteSpace(accessorBlocks)
				? fieldLines
				: fieldLines + Environment.NewLine + Environment.NewLine + accessorBlocks;
			return Template.Render(_STRUCT_FILE_TEMPLATE, ("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader($"시트 '{table.Name}'")), ("NAMESPACE", Config.Namespace), ("SHEET_NAME", table.Name), ("STRUCT_NAME", table.StructName), ("MEMBER_BLOCKS", Indent(memberBlocks, 8)));
		}

		/// <summary>FK 컬럼이 가리키는 행을 데이터베이스에서 가져오는 getter를 만든다.</summary>
		private string CreateRefGetterBlock(ColumnSpec column)
		{
			SheetTable target = TablesByName[column.RefSheetName];
			return Template.Render(_REF_GETTER_BLOCK_TEMPLATE,
			                       ("FIELD_NAME", column.FieldName),
			                       ("TARGET_SHEET_NAME", target.Name),
			                       ("TARGET_STRUCT_NAME", target.StructName),
			                       ("METHOD_NAME", "Get" + Identifier.ToPascal(column.FieldName)),
			                       ("DATABASE_CLASS_NAME", Config.DatabaseClassName),
			                       ("DATABASE_GETTER", "Get" + Identifier.Sanitize(target.Name)));
		}

		/// <summary>List&lt;타입&gt; FK/DK의 각 키가 가리키는 행 목록을 가져오는 getter를 만든다.</summary>
		private string CreateListRefGetterBlock(ColumnSpec column)
		{
			SheetTable target = TablesByName[column.RefSheetName];
			return Template.Render(_LIST_REF_GETTER_BLOCK_TEMPLATE,
			                       ("FIELD_NAME", column.FieldName),
			                       ("ROLE_NAME", column.Role == EColumnRole.ForeignKey ? "FK" : "DK"),
			                       ("TARGET_SHEET_NAME", target.Name),
			                       ("TARGET_STRUCT_NAME", target.StructName),
			                       ("METHOD_NAME", "Get" + Identifier.ToPascal(column.FieldName)),
			                       ("DATABASE_CLASS_NAME", Config.DatabaseClassName),
			                       ("DATABASE_GETTER", "Get" + Identifier.Sanitize(target.Name)));
		}

		/// <summary>부모 행에서 DK로 소속된 자식 행 목록을 가져오는 getter를 만든다.</summary>
		private string CreateDataGetterBlock(SheetTable parent, (SheetTable ChildTable, ColumnSpec DataKey) relation)
		{
			return Template.Render(_DATA_GETTER_BLOCK_TEMPLATE,
			                       ("CHILD_SHEET_NAME", relation.ChildTable.Name),
			                       ("CHILD_STRUCT_NAME", relation.ChildTable.StructName),
			                       ("METHOD_NAME", "Get" + Identifier.Sanitize(relation.ChildTable.Name)),
			                       ("DATABASE_CLASS_NAME", Config.DatabaseClassName),
			                       ("DATABASE_GETTER", DataGetterName(relation.ChildTable, relation.DataKey)),
			                       ("PRIMARY_KEY_FIELD_NAME", parent.PrimaryKeyColumn!.FieldName));
		}

		/// <summary>전체 시트 데이터를 담는 데이터베이스 클래스 코드를 생성한다.</summary>
		private string GenerateDatabase()
		{
			IReadOnlyList<SheetTable> keyedTables = Tables.Where(t => t.PrimaryKeyColumn != null).ToList();
			IReadOnlyList<(SheetTable ChildTable, ColumnSpec DataKey)> dataRelations = Tables
				.SelectMany(table => table.Columns.Where(c => c.Role == EColumnRole.DataKey).Select(c => (ChildTable: table, DataKey: c)))
				.ToList();
			string sheetArrayFields = string.Join(Environment.NewLine, Tables.Select(CreateSheetArrayField));
			string indexFields = string.Join(Environment.NewLine + Environment.NewLine,
			                                 keyedTables.Select(CreateIndexFieldBlock).Concat(dataRelations.Select(CreateDataIndexFieldBlock)));
			string getterBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                  keyedTables.Select(CreateGetterBlock).Concat(dataRelations.Select(CreateDataDatabaseGetterBlock)));
			string indexBuildBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                      keyedTables.Select(CreateIndexBuildBlock).Concat(dataRelations.Select(CreateDataIndexBuildBlock)));

			return Template.Render
			(
				_DATABASE_FILE_TEMPLATE,
				("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("스프레드시트 전체 구성")),
				("NAMESPACE", Config.Namespace),
				("DATABASE_CLASS_NAME", Config.DatabaseClassName),
				("SHEET_ARRAY_FIELDS", Indent(sheetArrayFields, 8)),
				("INDEX_FIELDS", Indent(indexFields, 8)),
				("GETTER_BLOCKS", Indent(getterBlocks, 8)),
				("INDEX_BUILD_BLOCKS", Indent(indexBuildBlocks, 12))
			);
		}

		private string CreateDataIndexFieldBlock((SheetTable ChildTable, ColumnSpec DataKey) relation)
		{
			return Template.Render(_DATA_INDEX_FIELD_BLOCK_TEMPLATE,
			                       ("KEY_TYPE", CSharpScalarTypeOf(relation.DataKey)),
			                       ("CHILD_STRUCT_NAME", relation.ChildTable.StructName),
			                       ("INDEX_FIELD_NAME", DataIndexFieldName(relation.ChildTable, relation.DataKey)));
		}

		private string CreateDataDatabaseGetterBlock((SheetTable ChildTable, ColumnSpec DataKey) relation)
		{
			return Template.Render(_DATA_DATABASE_GETTER_BLOCK_TEMPLATE,
			                       ("KEY_TYPE", CSharpScalarTypeOf(relation.DataKey)),
			                       ("CHILD_STRUCT_NAME", relation.ChildTable.StructName),
			                       ("METHOD_NAME", DataGetterName(relation.ChildTable, relation.DataKey)),
			                       ("INDEX_FIELD_NAME", DataIndexFieldName(relation.ChildTable, relation.DataKey)));
		}

		private string CreateDataIndexBuildBlock((SheetTable ChildTable, ColumnSpec DataKey) relation)
		{
			return Template.Render(relation.DataKey.IsList ? _DATA_LIST_INDEX_BUILD_BLOCK_TEMPLATE : _DATA_INDEX_BUILD_BLOCK_TEMPLATE,
			                       ("KEY_TYPE", CSharpScalarTypeOf(relation.DataKey)),
			                       ("CHILD_STRUCT_NAME", relation.ChildTable.StructName),
			                       ("CHILD_SHEET_NAME", Identifier.Sanitize(relation.ChildTable.Name)),
			                       ("DATA_KEY_FIELD_NAME", relation.DataKey.FieldName),
			                       ("INDEX_FIELD_NAME", DataIndexFieldName(relation.ChildTable, relation.DataKey)));
		}

		private IReadOnlyList<(SheetTable ChildTable, ColumnSpec DataKey)> OwnedDataOf(SheetTable parent)
		{
			return Tables.SelectMany(table => table.Columns
			                                       .Where(c => c.Role == EColumnRole.DataKey &&
			                                                   string.Equals(c.RefSheetName, parent.Name, StringComparison.OrdinalIgnoreCase))
			                                       .Select(c => (ChildTable: table, DataKey: c)))
			             .ToList();
		}

		private static string DataGetterName(SheetTable childTable, ColumnSpec dataKey)
		{
			return "Get" + Identifier.Sanitize(childTable.Name) + "By" + Identifier.ToPascal(dataKey.FieldName);
		}

		private static string DataIndexFieldName(SheetTable childTable, ColumnSpec dataKey)
		{
			return "_" + Identifier.ToCamel(Identifier.Sanitize(childTable.Name)) + "By" + Identifier.ToPascal(dataKey.FieldName);
		}

		/// <summary>시트 배열의 Key 인덱스 필드 코드 블록을 만든다.</summary>
		private string CreateIndexFieldBlock(SheetTable table)
		{
			return Template.Render(_INDEX_FIELD_BLOCK_TEMPLATE, ("KEY_TYPE", CSharpScalarTypeOf(table.PrimaryKeyColumn!)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트 배열 필드 코드 줄을 만든다.</summary>
		private static string CreateSheetArrayField(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			return $"public {table.StructName}[] {sheetName} = Array.Empty<{table.StructName}>();";
		}

		/// <summary>시트별 Getter와 TryGetter 코드 블록을 만든다.</summary>
		private string CreateGetterBlock(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			ColumnSpec primaryKey = table.PrimaryKeyColumn!;
			return Template.Render(_GETTER_BLOCK_TEMPLATE, ("SHEET_NAME", sheetName), ("ORIGINAL_SHEET_NAME", table.Name), ("KEY_FIELD_NAME", primaryKey.FieldName), ("KEY_TYPE", CSharpScalarTypeOf(primaryKey)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트별 Key 인덱스 구성 코드 블록을 만든다.</summary>
		private string CreateIndexBuildBlock(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			ColumnSpec primaryKey = table.PrimaryKeyColumn!;
			return Template.Render(_INDEX_BUILD_BLOCK_TEMPLATE, ("SHEET_NAME", sheetName), ("KEY_TYPE", CSharpScalarTypeOf(primaryKey)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)), ("KEY_FIELD_NAME", primaryKey.FieldName));
		}

		/// <summary>시트별 Key 인덱스 필드 이름을 만든다.</summary>
		private static string IndexFieldName(SheetTable table)
		{
			return "_" + Identifier.ToCamel(Identifier.Sanitize(table.Name)) + "ByKey";
		}
	}
}
