using DataBuilder.Configuration;
using DataBuilder.Model;

namespace DataBuilder.CodeGen
{
	/// <summary>시트 정의로부터 Unreal용 C++ USTRUCT 헤더 코드를 생성한다.</summary>
	public sealed class UnrealCodeGenerator : CodeGeneratorBase
	{
		private const string _TEMPLATE_FILE_NAME = "UnrealCodeTemplate.txt";
		private const string _ENUMS_FILE_TEMPLATE = "ENUMS_FILE";
		private const string _ENUM_BLOCK_TEMPLATE = "ENUM_BLOCK";
		private const string _STRUCT_FILE_TEMPLATE = "STRUCT_FILE";
		private const string _PROPERTY_BLOCK_TEMPLATE = "PROPERTY_BLOCK";
		private const string _STRUCT_REF_GETTER_BLOCK_TEMPLATE = "STRUCT_REF_GETTER_BLOCK";
		private const string _DATABASE_FILE_TEMPLATE = "DATABASE_FILE";
		private const string _SHEET_ARRAY_FIELD_TEMPLATE = "SHEET_ARRAY_FIELD";
		private const string _INDEX_FIELD_BLOCK_TEMPLATE = "INDEX_FIELD_BLOCK";
		private const string _GETTER_BLOCK_TEMPLATE = "GETTER_BLOCK";
		private const string _INDEX_BUILD_BLOCK_TEMPLATE = "INDEX_BUILD_BLOCK";

		/// <summary>Unreal 코드 생성에 필요한 설정과 시트 모델을 보관한다.</summary>
		public UnrealCodeGenerator(BuilderConfig config, IReadOnlyList<SheetTable> tables, EnumRegistry enums, bool force) : base(
			config, tables, enums, force, _TEMPLATE_FILE_NAME) {}

		/// <summary>enum, 시트 구조체, 데이터베이스 구조체 헤더를 모두 생성한다.</summary>
		public override void GenerateAll()
		{
			Directory.CreateDirectory(Config.StructOutputDirectory);
			Directory.CreateDirectory(Config.DatabaseOutputDirectory);

			if (Enums.IsEmpty == false)
			{
				string enumPath = Path.Combine(Config.StructOutputDirectory, "SheetEnums.h");
				Report(enumPath, WriteFile(enumPath, EnumsHash(), GenerateEnums));
			}

			foreach (SheetTable table in Tables)
			{
				string structPath = Path.Combine(Config.StructOutputDirectory, UnrealRowStructName(table) + ".h");
				Report(structPath, WriteFile(structPath, table.Hash, () => GenerateStruct(table)));
			}

			string databasePath = Path.Combine(Config.DatabaseOutputDirectory, UnrealDatabaseStructName() + ".h");
			Report(databasePath, WriteFile(databasePath, DatabaseHash(), GenerateDatabase));
		}

		/// <summary>시트 enum 컬럼에서 Unreal UENUM 코드를 생성한다.</summary>
		private string GenerateEnums()
		{
			string enumBlocks = string.Join(Environment.NewLine + Environment.NewLine, Enums.Enums.Select(CreateEnumBlock));
			return Template.Render(_ENUMS_FILE_TEMPLATE, ("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("시트의 enum: 컬럼")), ("ENUM_BLOCKS", enumBlocks));
		}

		/// <summary>UENUM 타입 코드 블록을 만든다.</summary>
		private string CreateEnumBlock(KeyValuePair<string, List<string>> enumPair)
		{
			string members = string.Join(Environment.NewLine, enumPair.Value.Select(member => $"{member} UMETA(DisplayName = \"{member}\"),"));
			return Template.Render(_ENUM_BLOCK_TEMPLATE, ("ENUM_NAME", enumPair.Key), ("ENUM_MEMBERS", Indent(members, 4)));
		}

		/// <summary>컬럼이 Unreal C++ 코드에서 갖는 타입 이름. ref 컬럼은 대상 시트 Key 컬럼의 타입을 따른다.</summary>
		private string UnrealTypeOf(ColumnSpec column)
		{
			switch (column.Type)
			{
				case EColumnType.Int: return "int32";

				case EColumnType.Long: return "int64";

				case EColumnType.Float: return "float";

				case EColumnType.Double: return "double";

				case EColumnType.Bool: return "bool";

				case EColumnType.String: return "FString";

				case EColumnType.Enum: return column.EnumName;

				case EColumnType.Ref: return UnrealTypeOf(TablesByName[column.RefSheetName].KeyColumn);

				default: throw new InvalidOperationException($"지원하지 않는 컬럼 타입입니다: {column.Type}");
			}
		}

		/// <summary>UPROPERTY 필드의 기본값을 만든다.</summary>
		private string UnrealDefaultValueOf(ColumnSpec column)
		{
			switch (column.Type)
			{
				case EColumnType.Int:
				case EColumnType.Long: return "0";

				case EColumnType.Float: return "0.0f";

				case EColumnType.Double: return "0.0";

				case EColumnType.Bool: return "false";

				case EColumnType.String: return "TEXT(\"\")";

				case EColumnType.Enum: return $"static_cast<{column.EnumName}>(0)";

				case EColumnType.Ref: return UnrealDefaultValueOf(TablesByName[column.RefSheetName].KeyColumn);

				default: throw new InvalidOperationException($"지원하지 않는 컬럼 타입입니다: {column.Type}");
			}
		}

		/// <summary>시트 하나에 대응하는 Unreal 행 USTRUCT 헤더를 생성한다.</summary>
		private string GenerateStruct(SheetTable table)
		{
			string propertyBlocks = string.Join(Environment.NewLine + Environment.NewLine, table.Columns.Select(CreatePropertyBlock));
			string refGetterBlocks = string.Join(Environment.NewLine + Environment.NewLine,
			                                     table.Columns.Where(c => c.Type == EColumnType.Ref).Select(CreateStructRefGetterBlock));

			string memberBlocks = string.IsNullOrWhiteSpace(refGetterBlocks)
				? propertyBlocks
				: propertyBlocks + Environment.NewLine + Environment.NewLine + refGetterBlocks;

			string enumInclude = table.Columns.Any(c => c.Type == EColumnType.Enum) ? "#include \"SheetEnums.h\"" : string.Empty;

			return Template.Render
			(
				_STRUCT_FILE_TEMPLATE,
				("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader($"시트 '{table.Name}'")),
				("ENUM_INCLUDE", enumInclude),
				("STRUCT_NAME", UnrealRowStructName(table)),
				("SHEET_NAME", table.Name),
				("MEMBER_BLOCKS", Indent(memberBlocks, 4))
			);
		}

		/// <summary>UPROPERTY 필드 코드 블록을 만든다.</summary>
		private string CreatePropertyBlock(ColumnSpec column)
		{
			return Template.Render(_PROPERTY_BLOCK_TEMPLATE, ("TYPE", UnrealTypeOf(column)), ("FIELD_NAME", column.FieldName),
			                       ("DEFAULT_VALUE", UnrealDefaultValueOf(column)));
		}

		/// <summary>ref 컬럼이 가리키는 행을 데이터베이스에서 가져오는 행 구조체 helper를 만든다.</summary>
		private string CreateStructRefGetterBlock(ColumnSpec column)
		{
			SheetTable target = TablesByName[column.RefSheetName];
			string methodName = "Get"     + Identifier.ToPascal(column.FieldName);
			string databaseGetter = "Get" + Identifier.Sanitize(target.Name);
			return Template.Render(_STRUCT_REF_GETTER_BLOCK_TEMPLATE, ("FIELD_NAME", column.FieldName), ("TARGET_SHEET_NAME", target.Name),
			                       ("TARGET_STRUCT_NAME", UnrealRowStructName(target)), ("METHOD_NAME", methodName), ("DATABASE_GETTER", databaseGetter));
		}

		/// <summary>전체 시트 데이터를 담는 Unreal 데이터베이스 USTRUCT 헤더를 생성한다.</summary>
		private string GenerateDatabase()
		{
			string structIncludes = string.Join(Environment.NewLine, Tables.Select(CreateStructInclude));
			string sheetArrayFields = string.Join(Environment.NewLine + Environment.NewLine, Tables.Select(CreateSheetArrayField));
			string indexFields = string.Join(Environment.NewLine      + Environment.NewLine, Tables.Select(CreateIndexFieldBlock));
			string getterBlocks = string.Join(Environment.NewLine     + Environment.NewLine, Tables.Select(CreateGetterBlock));
			string indexBuildBlocks = string.Join(Environment.NewLine + Environment.NewLine, Tables.Select(CreateIndexBuildBlock));

			return Template.Render
			(
				_DATABASE_FILE_TEMPLATE,
				("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("스프레드시트 전체 구성")),
				("STRUCT_INCLUDES", structIncludes),
				("DATABASE_STRUCT_NAME", UnrealDatabaseStructName()),
				("SHEET_ARRAY_FIELDS", Indent(sheetArrayFields, 4)),
				("INDEX_FIELDS", Indent(indexFields, 4)),
				("GETTER_BLOCKS", Indent(getterBlocks, 4)),
				("INDEX_BUILD_BLOCKS", Indent(indexBuildBlocks, 8))
			);
		}

		/// <summary>데이터베이스 헤더 기준의 행 구조체 헤더 include 줄을 만든다.</summary>
		private string CreateStructInclude(SheetTable table)
		{
			string headerPath = Path.Combine(Config.StructOutputDirectory, UnrealRowStructName(table) + ".h");
			string includePath = Path.GetRelativePath(Config.DatabaseOutputDirectory, headerPath).Replace('\\', '/');
			return $"#include \"{includePath}\"";
		}

		/// <summary>데이터베이스에 들어갈 시트 배열 UPROPERTY 블록을 만든다.</summary>
		private string CreateSheetArrayField(SheetTable table)
		{
			return Template.Render(_SHEET_ARRAY_FIELD_TEMPLATE, ("STRUCT_NAME", UnrealRowStructName(table)), ("SHEET_NAME", Identifier.Sanitize(table.Name)));
		}

		/// <summary>시트 배열의 Key 인덱스 필드 코드 블록을 만든다.</summary>
		private string CreateIndexFieldBlock(SheetTable table)
		{
			return Template.Render(_INDEX_FIELD_BLOCK_TEMPLATE, ("KEY_TYPE", UnrealTypeOf(table.KeyColumn)), ("STRUCT_NAME", UnrealRowStructName(table)),
			                       ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트별 Find/Get/TryGet 코드 블록을 만든다.</summary>
		private string CreateGetterBlock(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			return Template.Render(_GETTER_BLOCK_TEMPLATE, ("SHEET_NAME", sheetName), ("ORIGINAL_SHEET_NAME", table.Name),
			                       ("KEY_PARAMETER_TYPE", UnrealParameterTypeOf(table.KeyColumn)), ("STRUCT_NAME", UnrealRowStructName(table)),
			                       ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트별 Key 인덱스 구성 코드 블록을 만든다.</summary>
		private string CreateIndexBuildBlock(SheetTable table)
		{
			return Template.Render(_INDEX_BUILD_BLOCK_TEMPLATE, ("SHEET_NAME", Identifier.Sanitize(table.Name)), ("STRUCT_NAME", UnrealRowStructName(table)),
			                       ("INDEX_FIELD_NAME", IndexFieldName(table)), ("KEY_FIELD_NAME", table.KeyColumn.FieldName));
		}

		/// <summary>Unreal 함수 인자에 쓸 Key 타입 이름을 만든다.</summary>
		private string UnrealParameterTypeOf(ColumnSpec column)
		{
			string typeName = UnrealTypeOf(column);
			return typeName == "FString" ? "const FString&" : typeName;
		}

		/// <summary>Unreal 행 구조체 이름을 만든다.</summary>
		private static string UnrealRowStructName(SheetTable table)
		{
			return "F" + Identifier.Sanitize(table.Name) + "Row";
		}

		/// <summary>Unreal 데이터베이스 구조체 이름을 만든다.</summary>
		private string UnrealDatabaseStructName()
		{
			return Identifier.EnsurePrefix(Identifier.Sanitize(Config.DatabaseClassName), "F");
		}

		/// <summary>시트별 Key 인덱스 필드 이름을 만든다.</summary>
		private static string IndexFieldName(SheetTable table)
		{
			return Identifier.ToPascal(Identifier.Sanitize(table.Name)) + "ByKey";
		}
	}
}