// SheetHash: 9C4C8C7F3C627F56D414285361246C043AF5CBE79F04C235D31ABDC27CA35838
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 스프레드시트 전체 구성
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Generated.Schema
{
    /// <summary>
    /// 모든 시트 데이터를 담는 데이터베이스.
    /// (pk) 컬럼으로 시트 행을 조회하고 (fk) 컬럼으로 연결된 행을 참조한다.
    /// DataBuilder가 출력한 Json을 SheetDataBase.FromJson(json)으로 읽어 사용한다.
    /// </summary>
    [Serializable]
    public partial class SheetDataBase
    {
        public SStageRow[] Stage = Array.Empty<SStageRow>();
        public SMineRow[] Mine = Array.Empty<SMineRow>();
        public SMine_StatRow[] Mine_Stat = Array.Empty<SMine_StatRow>();
        public SLooseRow[] Loose = Array.Empty<SLooseRow>();

        [NonSerialized]
        private bool _indexBuilt;

        [NonSerialized]
        private Dictionary<int, SStageRow> _stageByKey;

        [NonSerialized]
        private Dictionary<int, SMineRow> _mineByKey;

        [NonSerialized]
        private Dictionary<int, SMine_StatRow> _mine_StatByKey;

        /// <summary>키(Stage_ID)로 'Stage' 시트의 행을 가져온다.</summary>
        public SStageRow GetStage(int key)
        {
            BuildIndex();
            SStageRow row;
            if (_stageByKey.TryGetValue(key, out row))
            {
                return row;
            }

            throw new KeyNotFoundException("'Stage' 시트에 없는 키입니다: " + key);
        }

        /// <summary>키(Stage_ID)로 'Stage' 시트의 행을 찾는다.</summary>
        public bool TryGetStage(int key, out SStageRow row)
        {
            BuildIndex();
            return _stageByKey.TryGetValue(key, out row);
        }

        /// <summary>키(Mine_ID)로 'Mine' 시트의 행을 가져온다.</summary>
        public SMineRow GetMine(int key)
        {
            BuildIndex();
            SMineRow row;
            if (_mineByKey.TryGetValue(key, out row))
            {
                return row;
            }

            throw new KeyNotFoundException("'Mine' 시트에 없는 키입니다: " + key);
        }

        /// <summary>키(Mine_ID)로 'Mine' 시트의 행을 찾는다.</summary>
        public bool TryGetMine(int key, out SMineRow row)
        {
            BuildIndex();
            return _mineByKey.TryGetValue(key, out row);
        }

        /// <summary>키(Mine_Stat_ID)로 'Mine_Stat' 시트의 행을 가져온다.</summary>
        public SMine_StatRow GetMine_Stat(int key)
        {
            BuildIndex();
            SMine_StatRow row;
            if (_mine_StatByKey.TryGetValue(key, out row))
            {
                return row;
            }

            throw new KeyNotFoundException("'Mine_Stat' 시트에 없는 키입니다: " + key);
        }

        /// <summary>키(Mine_Stat_ID)로 'Mine_Stat' 시트의 행을 찾는다.</summary>
        public bool TryGetMine_Stat(int key, out SMine_StatRow row)
        {
            BuildIndex();
            return _mine_StatByKey.TryGetValue(key, out row);
        }

        /// <summary>시트별 Key 인덱스를 구성한다.</summary>
        private void BuildIndex()
        {
            if (_indexBuilt)
            {
                return;
            }

            _stageByKey = new Dictionary<int, SStageRow>(Stage.Length);
            for (int i = 0; i < Stage.Length; i++)
            {
                _stageByKey[Stage[i].Stage_ID] = Stage[i];
            }

            _mineByKey = new Dictionary<int, SMineRow>(Mine.Length);
            for (int i = 0; i < Mine.Length; i++)
            {
                _mineByKey[Mine[i].Mine_ID] = Mine[i];
            }

            _mine_StatByKey = new Dictionary<int, SMine_StatRow>(Mine_Stat.Length);
            for (int i = 0; i < Mine_Stat.Length; i++)
            {
                _mine_StatByKey[Mine_Stat[i].Mine_Stat_ID] = Mine_Stat[i];
            }

            _indexBuilt = true;
        }

        /// <summary>Json 문자열에서 SheetDataBase 인스턴스를 생성한다.</summary>
        public static SheetDataBase FromJson(string json)
        {
#if UNITY_5_3_OR_NEWER
            return UnityEngine.JsonUtility.FromJson<SheetDataBase>(json);
#else
            System.Text.Json.JsonSerializerOptions options = new System.Text.Json.JsonSerializerOptions { IncludeFields = true };

            return System.Text.Json.JsonSerializer.Deserialize<SheetDataBase>(json, options);
#endif
        }

        /// <summary>현재 데이터베이스를 Json 문자열로 변환한다.</summary>
        public string ToJson()
        {
#if UNITY_5_3_OR_NEWER
            return UnityEngine.JsonUtility.ToJson(this, true);
#else
            System.Text.Json.JsonSerializerOptions options = new System.Text.Json.JsonSerializerOptions { IncludeFields = true, WriteIndented = true };

            return System.Text.Json.JsonSerializer.Serialize(this, options);
#endif
        }
    }
}