// SheetHash: 9C4C8C7F3C627F56D414285361246C043AF5CBE79F04C235D31ABDC27CA35838
// <auto-generated>
//     DataBuilder가 생성한 파일입니다. 직접 수정하지 마십시오.
//     원본: 스프레드시트 전체 구성
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "../Structs/FStageRow.h"
#include "../Structs/FMineRow.h"
#include "../Structs/FMine_StatRow.h"
#include "../Structs/FLooseRow.h"
#include "FSheetDataBase.generated.h"

/// <summary>모든 시트 데이터를 담는 데이터베이스. (pk)로 조회하고 (fk)로 연결된 행을 참조한다.</summary>
USTRUCT(BlueprintType)
struct FSheetDataBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FStageRow> Stage;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FMineRow> Mine;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FMine_StatRow> Mine_Stat;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLooseRow> Loose;

private:
    bool bIndexBuilt = false;

    TMap<int32, FStageRow> StageByKey;

    TMap<int32, FMineRow> MineByKey;

    TMap<int32, FMine_StatRow> Mine_StatByKey;

public:
    FStageRow* FindStage(int32 Key)
    {
        BuildIndex();
        return StageByKey.Find(Key);
    }

    const FStageRow& GetStage(int32 Key)
    {
        FStageRow* Row = FindStage(Key);
        if (Row != nullptr)
        {
            return *Row;
        }

        checkf(false, TEXT("'Stage' 시트에 없는 키입니다."));
        static const FStageRow EmptyRow{};
        return EmptyRow;
    }

    bool TryGetStage(int32 Key, FStageRow& OutRow)
    {
        if (FStageRow* Row = FindStage(Key))
        {
            OutRow = *Row;
            return true;
        }

        return false;
    }

    FMineRow* FindMine(int32 Key)
    {
        BuildIndex();
        return MineByKey.Find(Key);
    }

    const FMineRow& GetMine(int32 Key)
    {
        FMineRow* Row = FindMine(Key);
        if (Row != nullptr)
        {
            return *Row;
        }

        checkf(false, TEXT("'Mine' 시트에 없는 키입니다."));
        static const FMineRow EmptyRow{};
        return EmptyRow;
    }

    bool TryGetMine(int32 Key, FMineRow& OutRow)
    {
        if (FMineRow* Row = FindMine(Key))
        {
            OutRow = *Row;
            return true;
        }

        return false;
    }

    FMine_StatRow* FindMine_Stat(int32 Key)
    {
        BuildIndex();
        return Mine_StatByKey.Find(Key);
    }

    const FMine_StatRow& GetMine_Stat(int32 Key)
    {
        FMine_StatRow* Row = FindMine_Stat(Key);
        if (Row != nullptr)
        {
            return *Row;
        }

        checkf(false, TEXT("'Mine_Stat' 시트에 없는 키입니다."));
        static const FMine_StatRow EmptyRow{};
        return EmptyRow;
    }

    bool TryGetMine_Stat(int32 Key, FMine_StatRow& OutRow)
    {
        if (FMine_StatRow* Row = FindMine_Stat(Key))
        {
            OutRow = *Row;
            return true;
        }

        return false;
    }

private:
    void BuildIndex()
    {
        if (bIndexBuilt)
        {
            return;
        }

        StageByKey.Empty(Stage.Num());
        for (const FStageRow& Row : Stage)
        {
            StageByKey.Add(Row.Stage_ID, Row);
        }

        MineByKey.Empty(Mine.Num());
        for (const FMineRow& Row : Mine)
        {
            MineByKey.Add(Row.Mine_ID, Row);
        }

        Mine_StatByKey.Empty(Mine_Stat.Num());
        for (const FMine_StatRow& Row : Mine_Stat)
        {
            Mine_StatByKey.Add(Row.Mine_Stat_ID, Row);
        }

        bIndexBuilt = true;
    }
};