using DataBuilder.Configuration;
using DataBuilder.Model;

namespace DataBuilder.CodeGen
{
	/// <summary>
	/// 시트 정의로부터 Unity용 C# 코드를 생성한다.
	/// 모든 생성 파일의 첫 줄에는 "// SheetHash: ..." 주석이 달리며,
	/// 같은 해시를 가진 파일이 이미 있으면 다시 생성하지 않고 그 파일을 사용한다.
	/// </summary>
	public sealed class UnityCodeGenerator : CodeGeneratorBase
	{
		private const string _TEMPLATE_FILE_NAME = "UnityCodeTemplates.txt";
		private const string _ENUMS_FILE_TEMPLATE = "ENUMS_FILE";
		private const string _ENUM_BLOCK_TEMPLATE = "ENUM_BLOCK";
		private const string _STRUCT_FILE_TEMPLATE = "STRUCT_FILE";
		private const string _REF_GETTER_BLOCK_TEMPLATE = "REF_GETTER_BLOCK";
		private const string _DATABASE_FILE_TEMPLATE = "DATABASE_FILE";
		private const string _INDEX_FIELD_BLOCK_TEMPLATE = "INDEX_FIELD_BLOCK";
		private const string _GETTER_BLOCK_TEMPLATE = "GETTER_BLOCK";
		private const string _INDEX_BUILD_BLOCK_TEMPLATE = "INDEX_BUILD_BLOCK";

		/// <summary>Unity 코드 생성에 필요한 설정과 시트 모델을 보관한다.</summary>
		public UnityCodeGenerator(BuilderConfig config, IReadOnlyList<SheetTable> tables, EnumRegistry enums, bool force) : base(config, tables, enums, force, _TEMPLATE_FILE_NAME)
		{
		}

		/// <summary>enum, 시트 구조체, 데이터베이스 클래스를 모두 생성한다.</summary>
		public override void GenerateAll()
		{
			Directory.CreateDirectory(Config.StructOutputDirectory);
			Directory.CreateDirectory(Config.DatabaseOutputDirectory);

			if (Enums.IsEmpty == false)
			{
				string enumPath = Path.Combine(Config.StructOutputDirectory, "SheetEnums.g.cs");
				Report(enumPath, WriteFile(enumPath, EnumsHash(), GenerateEnums));
			}

			foreach (SheetTable table in Tables)
			{
				string structPath = Path.Combine(Config.StructOutputDirectory, table.StructName + ".g.cs");
				Report(structPath, WriteFile(structPath, table.Hash, () => GenerateStruct(table)));
			}

			string databasePath = Path.Combine(Config.DatabaseOutputDirectory, Config.DatabaseClassName + ".g.cs");
			Report(databasePath, WriteFile(databasePath, DatabaseHash(), GenerateDatabase));
		}

		/// <summary>시트 enum 컬럼에서 enum 코드를 생성한다.</summary>
		private string GenerateEnums()
		{
			string enumBlocks = string.Join(Environment.NewLine + Environment.NewLine, Enums.Enums.Select(CreateEnumBlock));
			return Template.Render(_ENUMS_FILE_TEMPLATE, ("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("시트의 enum: 컬럼")), ("NAMESPACE", Config.Namespace), ("ENUM_BLOCKS", Indent(enumBlocks, 4)));
		}

		/// <summary>enum 타입 코드 블록을 만든다.</summary>
		private string CreateEnumBlock(KeyValuePair<string, List<string>> enumPair)
		{
			string members = string.Join(Environment.NewLine, enumPair.Value.Select((member, index) => $"{member} = {index},"));
			return Template.Render(_ENUM_BLOCK_TEMPLATE, ("ENUM_NAME", enumPair.Key), ("ENUM_MEMBERS", Indent(members, 4)));
		}

		/// <summary>컬럼이 C# 코드에서 갖는 타입 이름. ref 컬럼은 대상 시트 Key 컬럼의 타입을 따른다.</summary>
		private string CSharpTypeOf(ColumnSpec column)
		{
			return column.Kind switch
			{
				EColumnKind.Int => "int",
				EColumnKind.Long => "long",
				EColumnKind.Float => "float",
				EColumnKind.Double => "double",
				EColumnKind.Bool => "bool",
				EColumnKind.String => "string",
				EColumnKind.Enum => column.EnumName,
				EColumnKind.Ref => CSharpTypeOf(TablesByName[column.RefSheetName].KeyColumn),
				_ => throw new InvalidOperationException($"지원하지 않는 컬럼 타입입니다: {column.Kind}"),
			};
		}

		/// <summary>시트 하나에 대응하는 행 구조체 코드를 생성한다.</summary>
		private string GenerateStruct(SheetTable table)
		{
			string fieldLines = string.Join(Environment.NewLine, table.Columns.Select(column => $"public {CSharpTypeOf(column)} {column.FieldName};"));
			string refGetterBlocks = string.Join(Environment.NewLine + Environment.NewLine, table.Columns.Where(c => c.Kind == EColumnKind.Ref).Select(column => CreateRefGetterBlock(table, column)));
			string memberBlocks = string.IsNullOrWhiteSpace(refGetterBlocks) ? fieldLines : fieldLines + Environment.NewLine + Environment.NewLine + refGetterBlocks;
			return Template.Render(_STRUCT_FILE_TEMPLATE, ("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader($"시트 '{table.Name}'")), ("NAMESPACE", Config.Namespace), ("SHEET_NAME", table.Name), ("STRUCT_NAME", table.StructName), ("MEMBER_BLOCKS", Indent(memberBlocks, 8)));
		}

		/// <summary>ref 컬럼 Getter 코드 블록을 만든다.</summary>
		private string CreateRefGetterBlock(SheetTable table, ColumnSpec column)
		{
			SheetTable target = TablesByName[column.RefSheetName];
			string methodName = "Get" + Identifier.ToPascal(column.FieldName);
			string databaseGetter = "Get" + Identifier.Sanitize(target.Name);
			return Template.Render(_REF_GETTER_BLOCK_TEMPLATE, ("FIELD_NAME", column.FieldName), ("TARGET_SHEET_NAME", target.Name), ("TARGET_STRUCT_NAME", target.StructName), ("METHOD_NAME", methodName), ("DATABASE_CLASS_NAME", Config.DatabaseClassName), ("DATABASE_GETTER", databaseGetter));
		}

		/// <summary>전체 시트 데이터를 담는 데이터베이스 클래스 코드를 생성한다.</summary>
		private string GenerateDatabase()
		{
			string sheetArrayFields = string.Join(Environment.NewLine, Tables.Select(CreateSheetArrayField));
			string indexFields = string.Join(Environment.NewLine + Environment.NewLine, Tables.Select(CreateIndexFieldBlock));
			string getterBlocks = string.Join(Environment.NewLine + Environment.NewLine, Tables.Select(CreateGetterBlock));
			string indexBuildBlocks = string.Join(Environment.NewLine + Environment.NewLine, Tables.Select(CreateIndexBuildBlock));

			return Template.Render
			(
				_DATABASE_FILE_TEMPLATE,
				("AUTO_GENERATED_HEADER", CreateAutoGeneratedHeader("스프레드시트 전체 구성")),
				("NAMESPACE", Config.Namespace),
				("DATABASE_CLASS_NAME", Config.DatabaseClassName),
				("SHEET_ARRAY_FIELDS", Indent(sheetArrayFields, 8)),
				("INDEX_FIELDS", Indent(indexFields, 8)),
				("GETTER_BLOCKS", Indent(getterBlocks, 8)),
				("INDEX_BUILD_BLOCKS", Indent(indexBuildBlocks, 12))
			);
		}

		/// <summary>시트 배열의 Key 인덱스 필드 코드 블록을 만든다.</summary>
		private string CreateIndexFieldBlock(SheetTable table)
		{
			return Template.Render(_INDEX_FIELD_BLOCK_TEMPLATE, ("KEY_TYPE", CSharpTypeOf(table.KeyColumn)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트 배열 필드 코드 줄을 만든다.</summary>
		private static string CreateSheetArrayField(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			return $"public {table.StructName}[] {sheetName} = Array.Empty<{table.StructName}>();";
		}

		/// <summary>시트별 Getter와 TryGetter 코드 블록을 만든다.</summary>
		private string CreateGetterBlock(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			return Template.Render(_GETTER_BLOCK_TEMPLATE, ("SHEET_NAME", sheetName), ("ORIGINAL_SHEET_NAME", table.Name), ("KEY_FIELD_NAME", table.KeyColumn.FieldName), ("KEY_TYPE", CSharpTypeOf(table.KeyColumn)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)));
		}

		/// <summary>시트별 Key 인덱스 구성 코드 블록을 만든다.</summary>
		private string CreateIndexBuildBlock(SheetTable table)
		{
			string sheetName = Identifier.Sanitize(table.Name);
			return Template.Render(_INDEX_BUILD_BLOCK_TEMPLATE, ("SHEET_NAME", sheetName), ("KEY_TYPE", CSharpTypeOf(table.KeyColumn)), ("STRUCT_NAME", table.StructName), ("INDEX_FIELD_NAME", IndexFieldName(table)), ("KEY_FIELD_NAME", table.KeyColumn.FieldName));
		}

		/// <summary>시트별 Key 인덱스 필드 이름을 만든다.</summary>
		private static string IndexFieldName(SheetTable table)
		{
			return "_" + Identifier.ToCamel(Identifier.Sanitize(table.Name)) + "ByKey";
		}
	}
}
